name: Publish Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., 3.1.0)'
        required: true # Making it required for manual runs to avoid errors

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_step.outputs.version }}
    steps:
      - name: Determine version
        id: version_step
        run: |
          VERSION=""
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "Version determined: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: get-version
    # This check ensures we don't proceed if the version somehow ends up empty
    if: ${{ needs.get-version.outputs.version != '' }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
       username: ${{ vars.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:docker"
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          uvmaster/drozer-testbed:latest
          uvmaster/drozer-testbed:${{ needs.get-version.outputs.version }}
